<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VillageNamesSeeder extends Seeder
{
    public function run()
    {
        $villages = [
            // Taluka ID 1: ગાંધીનગર
            ['name' => 'અડાલજ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'આદરજ મોટી', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ઉનાવા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ઉવારસદ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'કાકાના તારાપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'જલુંદ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'જમીયતપુરા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ટીંટોડા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'તારાપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'દંતાલી', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'પીંપળજ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'પીંઢારડા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'પુન્દ્રાસણ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ભોયણ રાઠોડ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'રૂપાલ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'વાસન', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'શેરથા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'સરઢવ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'સોનીપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'આલમપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ઈસનપુર મોટા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'કાનપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ગલુદણ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ગિયોડ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ચંદ્રાલા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ચિલોડા(ડ)', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ચેખલારાણી', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'છાલા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'જાખોરા-રાજપુરા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ડભોડા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'દશેલા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'દોલારાણા વાસણા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'ધણપ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'નવાધરમપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'પિરોજપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'મગોડી', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'મહુન્દ્રા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'માધવગઢ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'મેદરા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'રાયપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'રતનપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'રણાસણ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'લેકાવાડા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'લવારપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'લીંબડીયા-કરાઈ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'વડોદરા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'વાંકા નેરડા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'વિરા તલાવડી', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'શાહપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'શિહોલી મોટી', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'સાદરા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'સોનારડા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'વલાદ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'વજાપુર', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'પ્રાતિયા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'પાલજ', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'મોતીપુરા', 'user_id' => 1, 'taluka_id' => 1],
            ['name' => 'મુબારકપુરા', 'user_id' => 1, 'taluka_id' => 1],

            // Taluka ID 2: કલોલ
            ['name' => 'ગણપતપુરા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'કાંઠા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'ભીમાસણ', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'પાનસર', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'દંતાલી', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'નવા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'હાજીપુર', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'જાસપુર', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'રામનગર', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'છત્રાલ', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'અઢાણા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'વેડા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'લોરકડી', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'વીરમણ', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'ગામડી', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'બિલવા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'ઘુઘળિયા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'જોધવાડા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'ઢેકલી', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'સંતલ', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'મોદે', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'દોડિયા', 'user_id' => 1, 'taluka_id' => 2],
            ['name' => 'નવાપુરા', 'user_id' => 1, 'taluka_id' => 2],

            // Taluka ID 3: દહેગામ
            ['name' => 'ચામલા', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'ડેમાલિયા', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'બહ્યાવા', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'દેવધાર', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'ધમકડ', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'નવનગર', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'પોરપટા', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'ભેડાળા', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'રેમાય પાટા', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'શીતલપુર', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'ભાદરસી', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'સરપાવડી', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'સુકલપાટી', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'સસ્રાવડી', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'અકેટ', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'માસાક', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'વિશ્વનાથ', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'ભાયલી', 'user_id' => 1, 'taluka_id' => 3],
            ['name' => 'કાવડવા', 'user_id' => 1, 'taluka_id' => 3],

            // Taluka ID 4: માણસા
            ['name' => 'અંબોડ', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'અનોડિયા', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'ભટ્ઠાર', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'દેડીયાપડ', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'દીલાડ', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'એલાસણ', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'નૈયર', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'મોરડી', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'મુકી', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'સોનાળા', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'સપલિયા', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'સમધયા', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'સાંગથર', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'સેવાપુર', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'ઉમરી', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'અકોલીયા', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'આટલી', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'સાલવિ', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'પાટણ', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'ધુસર', 'user_id' => 1, 'taluka_id' => 4],
            ['name' => 'રામપર', 'user_id' => 1, 'taluka_id' => 4],
        ];

        foreach ($villages as $village) {
            DB::table('village_names')->insert([
                'name' => $village['name'],
                'user_id' => $village['user_id'],
                'taluka_id' => $village['taluka_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
